name: Create Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Check Version Upgrade
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: filter
        id: filter
        uses: dorny/paths-filter@v2
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          filters: |
            mod_a:
              - 'mod_a/**'
            mod_b:
              - 'mod_b/**'

  create_tag:
    needs: changes
    name: Create and Push Tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: version
        run: echo "::set-output name=version::$(cat ${{matrix.package}}/VERSION)"
        id: version
      - name: tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a ${{matrix.package}}/v${{ steps.version.outputs.version }} -m ${{matrix.package}}/v${{ steps.version.outputs.version }}
          git push origin ${{matrix.package}}/v${{ steps.version.outputs.version }}
