name: Create Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  changes:
    uses: macmaad/golang-versioning/.github/workflows/detect-changes.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: changes
    name: Create and Push Tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: version
        run: echo "::set-output name=version::$(cat ${{matrix.package}}/VERSION)"
        id: version
      - name: tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a ${{matrix.package}}/v${{ steps.version.outputs.version }} -m ${{matrix.package}}/v${{ steps.version.outputs.version }}
          git push origin ${{matrix.package}}/v${{ steps.version.outputs.version }}
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          generate_release_notes: true
          name: ${{matrix.package}}/v${{ steps.version.outputs.version }}
          tag_name: ${{matrix.package}}/v${{ steps.version.outputs.version }}
          prerelease: false
